-- WorldBuilder.server.lua — Procedural surface environment around the dig site
-- Place in: ServerScriptService/WorldBuilder (Script)
--
-- The dig site itself (blocks, walls, spawn) is generated by DigSystem.
-- This script builds everything that makes the place read as a world:
-- surface ground, an excavation camp, pit-rim dressing, scatter props,
-- and lighting/atmosphere. Everything is procedural parts — no uploaded
-- assets, no Studio-placed dependencies.

local Lighting = game:GetService("Lighting")

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Config = require(ReplicatedStorage:WaitForChild("Config"))

-- Dig site footprint (mirrors DigSystem's grid math): blocks span
-- roughly ±(GRID_WIDTH * BLOCK_SIZE / 2) on x/z, top surface at y = +2.
local SITE_HALF = (Config.GRID_WIDTH * Config.BLOCK_SIZE) / 2 + 2 -- includes wall
local GROUND_EXTENT = 240 -- how far the surface ground reaches from origin
local GROUND_TOP_Y = 2    -- flush with the top of the depth-0 block layer

local environmentFolder = Instance.new("Folder")
environmentFolder.Name = "Environment"
environmentFolder.Parent = workspace

-- ═══════════════════════════════════════════════════════════════════
-- Clear Studio template leftovers
-- ═══════════════════════════════════════════════════════════════════

-- The Studio "Baseplate" template ships a solid slab with its top at y=0.
-- The dig grid descends through that volume, so the slab physically plugs
-- the pit one layer down and its SpawnLocation competes with the dig
-- site's. Remove both so the generated world is the only world.
local function clearTemplateLeftovers()
	local baseplate = workspace:FindFirstChild("Baseplate")
	if baseplate and baseplate:IsA("BasePart") then
		baseplate:Destroy()
	end

	local digSite = workspace:FindFirstChild("DigSite")
	for _, descendant in ipairs(workspace:GetChildren()) do
		if descendant:IsA("SpawnLocation") and (not digSite or not descendant:IsDescendantOf(digSite)) then
			descendant:Destroy()
		end
	end
end

-- ═══════════════════════════════════════════════════════════════════
-- Part helpers
-- ═══════════════════════════════════════════════════════════════════

local function makePart(props)
	local part = Instance.new(props.shape == "Wedge" and "WedgePart" or "Part")
	part.Anchored = true
	part.CanCollide = props.canCollide ~= false
	part.Material = props.material or Enum.Material.SmoothPlastic
	part.Color = props.color or Color3.fromRGB(160, 160, 160)
	part.Size = props.size
	if props.shape == "Cylinder" then
		part.Shape = Enum.PartType.Cylinder
	elseif props.shape == "Ball" then
		part.Shape = Enum.PartType.Ball
	end
	part.CFrame = props.cframe or CFrame.new(props.position or Vector3.zero)
	part.Name = props.name or "EnvPart"
	part.Parent = props.parent or environmentFolder
	return part
end

local function addSignText(part, face, text, textColor, textSize)
	local gui = Instance.new("SurfaceGui")
	gui.Face = face or Enum.NormalId.Front
	gui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	gui.PixelsPerStud = 32
	gui.Parent = part

	local label = Instance.new("TextLabel")
	label.Size = UDim2.fromScale(1, 1)
	label.BackgroundTransparency = 1
	label.Font = Enum.Font.GothamBold
	label.TextScaled = textSize == nil
	label.TextSize = textSize or 24
	label.TextColor3 = textColor or Color3.fromRGB(255, 235, 180)
	label.TextStrokeTransparency = 0.4
	label.TextWrapped = true
	label.Text = text
	label.Parent = gui

	return gui
end

-- ═══════════════════════════════════════════════════════════════════
-- Surface ground (ring around the pit)
-- ═══════════════════════════════════════════════════════════════════

local function buildGround()
	local groundColor = Color3.fromRGB(106, 127, 63)
	local span = GROUND_EXTENT * 2
	local ringWidth = GROUND_EXTENT - SITE_HALF
	local thickness = 4
	local y = GROUND_TOP_Y - thickness / 2

	-- Four slabs framing the pit opening: north, south, east, west.
	local slabs = {
		{ size = Vector3.new(span, thickness, ringWidth), pos = Vector3.new(0, y, -(SITE_HALF + ringWidth / 2)) },
		{ size = Vector3.new(span, thickness, ringWidth), pos = Vector3.new(0, y, SITE_HALF + ringWidth / 2) },
		{ size = Vector3.new(ringWidth, thickness, SITE_HALF * 2), pos = Vector3.new(-(SITE_HALF + ringWidth / 2), y, 0) },
		{ size = Vector3.new(ringWidth, thickness, SITE_HALF * 2), pos = Vector3.new(SITE_HALF + ringWidth / 2, y, 0) },
	}

	for _, slab in ipairs(slabs) do
		makePart({
			name = "Ground",
			size = slab.size,
			position = slab.pos,
			material = Enum.Material.Grass,
			color = groundColor,
		})
	end
end

-- ═══════════════════════════════════════════════════════════════════
-- Pit rim dressing: plank trim + corner posts with lanterns
-- ═══════════════════════════════════════════════════════════════════

local WOOD = Color3.fromRGB(121, 85, 53)
local WOOD_DARK = Color3.fromRGB(94, 64, 38)

local function buildLantern(position, parent)
	local post = makePart({
		name = "LanternPost",
		size = Vector3.new(0.8, 9, 0.8),
		position = position + Vector3.new(0, 4.5, 0),
		material = Enum.Material.Wood,
		color = WOOD_DARK,
		parent = parent,
	})

	local lamp = makePart({
		name = "LanternLamp",
		size = Vector3.new(1.4, 1.4, 1.4),
		position = position + Vector3.new(0, 9.5, 0),
		material = Enum.Material.Neon,
		color = Color3.fromRGB(255, 196, 92),
		canCollide = false,
		parent = parent,
	})

	local light = Instance.new("PointLight")
	light.Color = Color3.fromRGB(255, 196, 110)
	light.Brightness = 1.4
	light.Range = 24
	light.Parent = lamp

	return post
end

local function buildPitRim()
	local rim = Instance.new("Folder")
	rim.Name = "PitRim"
	rim.Parent = environmentFolder

	local trimY = GROUND_TOP_Y + 0.4
	local trimLen = SITE_HALF * 2 + 2

	-- Plank trim along all four edges of the opening
	for _, def in ipairs({
		{ size = Vector3.new(trimLen, 0.8, 2), pos = Vector3.new(0, trimY, -SITE_HALF) },
		{ size = Vector3.new(trimLen, 0.8, 2), pos = Vector3.new(0, trimY, SITE_HALF) },
		{ size = Vector3.new(2, 0.8, trimLen), pos = Vector3.new(-SITE_HALF, trimY, 0) },
		{ size = Vector3.new(2, 0.8, trimLen), pos = Vector3.new(SITE_HALF, trimY, 0) },
	}) do
		makePart({
			name = "RimPlank",
			size = def.size,
			position = def.pos,
			material = Enum.Material.WoodPlanks,
			color = WOOD,
			parent = rim,
		})
	end

	-- Lantern posts on the four corners
	for _, corner in ipairs({
		Vector3.new(-SITE_HALF, GROUND_TOP_Y, -SITE_HALF),
		Vector3.new(SITE_HALF, GROUND_TOP_Y, -SITE_HALF),
		Vector3.new(-SITE_HALF, GROUND_TOP_Y, SITE_HALF),
		Vector3.new(SITE_HALF, GROUND_TOP_Y, SITE_HALF),
	}) do
		buildLantern(corner, rim)
	end
end

-- ═══════════════════════════════════════════════════════════════════
-- Excavation camp (north of the pit)
-- ═══════════════════════════════════════════════════════════════════

local function buildStall(center, facing, signTitle, signBody, accentColor)
	local stall = Instance.new("Model")
	stall.Name = signTitle
	stall.Parent = environmentFolder

	local look = CFrame.lookAt(center, center + facing)

	-- Counter
	makePart({
		name = "Counter",
		size = Vector3.new(10, 3.4, 2.4),
		cframe = look * CFrame.new(0, 1.7, 0),
		material = Enum.Material.WoodPlanks,
		color = WOOD,
		parent = stall,
	})

	-- Posts
	for _, xOff in ipairs({ -4.4, 4.4 }) do
		makePart({
			name = "Post",
			size = Vector3.new(0.8, 9, 0.8),
			cframe = look * CFrame.new(xOff, 4.5, -0.6),
			material = Enum.Material.Wood,
			color = WOOD_DARK,
			parent = stall,
		})
	end

	-- Roof (slight overhang, tilted)
	makePart({
		name = "Roof",
		size = Vector3.new(11.5, 0.6, 5),
		cframe = look * CFrame.new(0, 9.2, -0.4) * CFrame.Angles(math.rad(-8), 0, 0),
		material = Enum.Material.WoodPlanks,
		color = accentColor,
		canCollide = false,
		parent = stall,
	})

	-- Sign board above the counter, facing the pit
	local sign = makePart({
		name = "Sign",
		size = Vector3.new(9, 2.4, 0.4),
		cframe = look * CFrame.new(0, 7.2, 0.2),
		material = Enum.Material.SmoothPlastic,
		color = Color3.fromRGB(38, 34, 30),
		canCollide = false,
		parent = stall,
	})
	addSignText(sign, Enum.NormalId.Back, signTitle, accentColor)

	-- Smaller how-to board on the counter front
	local board = makePart({
		name = "HowTo",
		size = Vector3.new(8, 1.6, 0.3),
		cframe = look * CFrame.new(0, 2.2, 1.45),
		material = Enum.Material.SmoothPlastic,
		color = Color3.fromRGB(48, 44, 40),
		canCollide = false,
		parent = stall,
	})
	addSignText(board, Enum.NormalId.Back, signBody, Color3.fromRGB(230, 230, 235), 20)

	return stall
end

local function buildCampfire(center)
	local fire = Instance.new("Model")
	fire.Name = "Campfire"
	fire.Parent = environmentFolder

	-- Log ring
	for i = 1, 5 do
		local angle = math.rad(i * 72)
		makePart({
			name = "Log",
			size = Vector3.new(3.4, 0.9, 0.9),
			cframe = CFrame.new(center) * CFrame.Angles(0, angle, 0) * CFrame.new(0, 0.45, 1.4) * CFrame.Angles(0, math.rad(90), 0),
			material = Enum.Material.Wood,
			color = WOOD_DARK,
			parent = fire,
		})
	end

	-- Glowing coals + flame particles + light
	local coals = makePart({
		name = "Coals",
		size = Vector3.new(1.8, 0.6, 1.8),
		position = center + Vector3.new(0, 0.5, 0),
		material = Enum.Material.Neon,
		color = Color3.fromRGB(255, 120, 30),
		canCollide = false,
		parent = fire,
	})

	local flames = Instance.new("ParticleEmitter")
	flames.Texture = "rbxasset://textures/particles/fire_main.dds"
	flames.Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 200, 90)),
		ColorSequenceKeypoint.new(0.5, Color3.fromRGB(255, 110, 30)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(120, 30, 10)),
	})
	flames.LightEmission = 0.85
	flames.Lifetime = NumberRange.new(0.5, 0.9)
	flames.Rate = 18
	flames.Speed = NumberRange.new(3, 5)
	flames.SpreadAngle = Vector2.new(12, 12)
	flames.Size = NumberSequence.new({
		NumberSequenceKeypoint.new(0, 1.6),
		NumberSequenceKeypoint.new(1, 0.2),
	})
	flames.Transparency = NumberSequence.new({
		NumberSequenceKeypoint.new(0, 0.2),
		NumberSequenceKeypoint.new(1, 1),
	})
	flames.Acceleration = Vector3.new(0, 6, 0)
	flames.Parent = coals

	local light = Instance.new("PointLight")
	light.Color = Color3.fromRGB(255, 150, 70)
	light.Brightness = 2
	light.Range = 28
	light.Parent = coals
end

local function buildTent(center, rotationY, color)
	local look = CFrame.new(center) * CFrame.Angles(0, rotationY, 0)
	for _, side in ipairs({ -1, 1 }) do
		makePart({
			name = "TentSide",
			shape = "Wedge",
			size = Vector3.new(7, 5, 4),
			cframe = look * CFrame.new(0, 2.5, side * 2) * CFrame.Angles(0, side == 1 and math.rad(180) or 0, 0),
			material = Enum.Material.Fabric,
			color = color,
		})
	end
end

local function buildCrates(center)
	for i = 1, 4 do
		local size = 2 + (i % 2)
		makePart({
			name = "Crate",
			size = Vector3.new(size, size, size),
			cframe = CFrame.new(center + Vector3.new((i - 2.5) * 3.2, size / 2 + GROUND_TOP_Y, (i % 2) * 2.4))
				* CFrame.Angles(0, math.rad(i * 23), 0),
			material = Enum.Material.WoodPlanks,
			color = Color3.fromRGB(141, 104, 66),
		})
	end
end

local function buildCamp()
	local campZ = -(SITE_HALF + 16)

	-- Big game sign on the north rim, readable from spawn inside the pit
	local billboard = makePart({
		name = "GameSign",
		size = Vector3.new(26, 7, 1),
		position = Vector3.new(0, GROUND_TOP_Y + 12, campZ - 14),
		material = Enum.Material.SmoothPlastic,
		color = Color3.fromRGB(32, 28, 26),
		canCollide = false,
	})
	addSignText(billboard, Enum.NormalId.Back, "⛏ DEEP DIG", Color3.fromRGB(255, 210, 80))
	for _, xOff in ipairs({ -11, 11 }) do
		makePart({
			name = "GameSignPost",
			size = Vector3.new(1.2, 14, 1.2),
			position = Vector3.new(xOff, GROUND_TOP_Y + 7, campZ - 14),
			material = Enum.Material.Wood,
			color = WOOD_DARK,
		})
	end

	-- Stalls flank the sign, facing the pit (+Z)
	buildStall(
		Vector3.new(-18, GROUND_TOP_Y, campZ),
		Vector3.new(0, 0, 1),
		"💰 SELL",
		"Sell finds with the Sell All button (bottom right)",
		Color3.fromRGB(255, 200, 70)
	)
	buildStall(
		Vector3.new(18, GROUND_TOP_Y, campZ),
		Vector3.new(0, 0, 1),
		"⬆ TOOL SHOP",
		"Upgrade your tool with the Upgrade button",
		Color3.fromRGB(120, 200, 255)
	)

	buildCampfire(Vector3.new(0, GROUND_TOP_Y, campZ + 2))
	buildTent(Vector3.new(-34, GROUND_TOP_Y, campZ - 4), math.rad(35), Color3.fromRGB(168, 92, 70))
	buildTent(Vector3.new(34, GROUND_TOP_Y, campZ - 6), math.rad(-20), Color3.fromRGB(96, 122, 168))
	buildCrates(Vector3.new(-30, 0, campZ + 10))
end

-- ═══════════════════════════════════════════════════════════════════
-- Scatter props: rocks and bushes on the surface ring
-- ═══════════════════════════════════════════════════════════════════

local function buildScatter()
	local scatter = Instance.new("Folder")
	scatter.Name = "Scatter"
	scatter.Parent = environmentFolder

	local placed = 0
	while placed < 26 do
		local x = math.random(-GROUND_EXTENT + 10, GROUND_EXTENT - 10)
		local z = math.random(-GROUND_EXTENT + 10, GROUND_EXTENT - 10)

		-- Keep the pit opening and the camp clear
		local inPit = math.abs(x) < SITE_HALF + 6 and math.abs(z) < SITE_HALF + 6
		local inCamp = math.abs(x) < 48 and z < -SITE_HALF and z > -(SITE_HALF + 40)
		if not inPit and not inCamp then
			placed = placed + 1
			if placed % 2 == 0 then
				local s = 2 + math.random() * 3
				makePart({
					name = "Rock",
					size = Vector3.new(s, s * 0.7, s * 0.9),
					cframe = CFrame.new(x, GROUND_TOP_Y + s * 0.25, z)
						* CFrame.Angles(math.rad(math.random(-12, 12)), math.rad(math.random(0, 360)), math.rad(math.random(-12, 12))),
					material = Enum.Material.Rock,
					color = Color3.fromRGB(118, 112, 104),
					parent = scatter,
				})
			else
				local s = 2.5 + math.random() * 2.5
				makePart({
					name = "Bush",
					shape = "Ball",
					size = Vector3.new(s, s, s),
					position = Vector3.new(x, GROUND_TOP_Y + s * 0.3, z),
					material = Enum.Material.Grass,
					color = Color3.fromRGB(78, 105, 48),
					canCollide = false,
					parent = scatter,
				})
			end
		end
	end
end

-- ═══════════════════════════════════════════════════════════════════
-- Lighting & atmosphere
-- ═══════════════════════════════════════════════════════════════════

local function setupLighting()
	Lighting.ClockTime = 14.3
	Lighting.Brightness = 2.4
	Lighting.Ambient = Color3.fromRGB(96, 92, 86)
	Lighting.OutdoorAmbient = Color3.fromRGB(128, 122, 110)
	Lighting.EnvironmentDiffuseScale = 0.6
	Lighting.EnvironmentSpecularScale = 0.4

	if not Lighting:FindFirstChildOfClass("Atmosphere") then
		local atmosphere = Instance.new("Atmosphere")
		atmosphere.Density = 0.32
		atmosphere.Offset = 0.4
		atmosphere.Color = Color3.fromRGB(210, 200, 185)
		atmosphere.Decay = Color3.fromRGB(120, 110, 95)
		atmosphere.Haze = 1.6
		atmosphere.Parent = Lighting
	end

	if not Lighting:FindFirstChildOfClass("BloomEffect") then
		local bloom = Instance.new("BloomEffect")
		bloom.Intensity = 0.4
		bloom.Size = 24
		bloom.Threshold = 1.2
		bloom.Parent = Lighting
	end

	if not Lighting:FindFirstChildOfClass("SunRaysEffect") then
		local sunRays = Instance.new("SunRaysEffect")
		sunRays.Intensity = 0.08
		sunRays.Spread = 0.6
		sunRays.Parent = Lighting
	end
end

-- ═══════════════════════════════════════════════════════════════════
-- Initialize
-- ═══════════════════════════════════════════════════════════════════

-- DigSystem generates its terrain at load; wait for its folder so the
-- baseplate/spawn cleanup can tell template spawns from the real one.
workspace:WaitForChild("DigSite", 10)

clearTemplateLeftovers()
buildGround()
buildPitRim()
buildCamp()
buildScatter()
setupLighting()
print("[DeepDig] WorldBuilder: surface environment ready")
